name: Silver Data Pipeline

permissions:
  contents: write
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas pdfplumber requests

      - name: Run pipeline
        run: python silver_pipeline.py

      - name: Commit CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add silver_oi.csv
          git commit -m "update silver data" || echo "No changes"
          git push
